### ISSUE TITLE
SSLError: hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'

### ISSUE THREAD

**Issue by mgaitan** [touchandgo-devs/touchandgo#78]
I'm getting the exception pasted below in a fresh install  

Touchandgo==0.12.4
KickassAPI==1.0.4

```
tin@morochita:~/lab/touchandgo$ touchandgo 'modern family' 1 2 --player chromecast
2015-09-22 21:56:34,173  touchandgo.main         INFO     Starting touchandgo
Traceback (most recent call last):
  File "/usr/local/bin/touchandgo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/main.py", line 71, in main
    touchandgo.watch()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/__init__.py", line 68, in watch
    self.search_magnet()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/__init__.py", line 81, in search_magnet
    self.kat_search()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/__init__.py", line 98, in kat_search
    results = Search(search_string).list()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 360, in __init__
    self.url = SearchUrl(query, page, category, order)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 141, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 163, in build
    self.max_page = self._get_max_page(ret)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 92, in _get_max_page
    html = requests.get(url).text
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 578, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 178, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'kat.cr' doesn't match either of '*.kickass.so', 'kickass.so'
```

**Comment by felipelerena** [comment]
this is supposed to be fixed upstream
