### ISSUE TITLE
Touchandgo crashes with all runs

### ISSUE THREAD

**Issue by javiermarcon** [touchandgo-devs/touchandgo#82]
I tried to run touchandgo but in every run it crashes with this traceback:

javier@javier-System-Product-Name:~$ touchandgo --verbose --nocache 2091
2016-10-21 10:25:55,657  touchandgo.main         INFO     Starting touchandgo
2016-10-21 10:25:55,658  touchandgo.main         DEBUG    Running Python sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0) on 'linux2'
2016-10-21 10:25:55,658  touchandgo.main         DEBUG    Libtorrent version: 0.16.13.0
Traceback (most recent call last):
  File "/usr/local/bin/touchandgo", line 9, in <module>
    load_entry_point('Touchandgo==0.13.3', 'console_scripts', 'touchandgo')()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/main.py", line 71, in main
    touchandgo.watch()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/**init**.py", line 69, in watch
    self.search_magnet()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/**init**.py", line 82, in search_magnet
    self.kat_search()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/**init**.py", line 99, in kat_search
    results = Search(search_string).list()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 357, in **init**
    self.url = SearchUrl(query, page, category, order)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 140, in **init**
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 162, in build
    self.max_page = self._get_max_page(ret)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 94, in _get_max_page
    tds = int(pq("h2").text().split()[-1])
IndexError: list index out of range
javier@javier-System-Product-Name:~$ touchandgo --verbose crysis
2016-10-21 10:29:02,656  touchandgo.main         INFO     Starting touchandgo
2016-10-21 10:29:02,656  touchandgo.main         DEBUG    Running Python sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0) on 'linux2'
2016-10-21 10:29:02,656  touchandgo.main         DEBUG    Libtorrent version: 0.16.13.0
Traceback (most recent call last):
  File "/usr/local/bin/touchandgo", line 9, in <module>
    load_entry_point('Touchandgo==0.13.3', 'console_scripts', 'touchandgo')()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/main.py", line 71, in main
    touchandgo.watch()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/__init__.py", line 69, in watch
    self.search_magnet()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/**init**.py", line 82, in search_magnet
    self.kat_search()
  File "/usr/local/lib/python2.7/dist-packages/touchandgo/search/**init**.py", line 99, in kat_search
    results = Search(search_string).list()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 357, in **init**
    self.url = SearchUrl(query, page, category, order)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 140, in **init**
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 162, in build
    self.max_page = self._get_max_page(ret)
  File "/usr/local/lib/python2.7/dist-packages/KickassAPI.py", line 94, in _get_max_page
    tds = int(pq("h2").text().split()[-1])
IndexError: list index out of range
javier@javier-System-Product-Name:~$ 

This happens in every run.

**Comment by nicoman** [comment]
http://kickass.to/ is down, thats the problem. Maybe we need a CR to use another torrent site.

**Comment by felipelerena** [comment]
Yep. KAT is down. I will change default soon and add some other source.
meanwhile you can add "--search tms" or "--search strike" they should work

**Comment by felipelerena** [comment]
I fixed it, added 1337x.to as only provider
